# Generated by Django 4.1.7 on 2023-04-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="pokemon", name="owner",),
    ]
