# Generated by Django 4.1.7 on 2023-04-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_pokemon_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon", name="img", field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name="Feeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Feeding Date")),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("B", "Breakfast"),
                            ("L", "Lunch"),
                            ("S", "Snack"),
                            ("D", "Dinner"),
                            ("T", "Treat"),
                        ],
                        default="B",
                        max_length=1,
                        verbose_name="Meal Type",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.pokemon",
                    ),
                ),
            ],
        ),
    ]
