# Generated by Django 4.1.7 on 2023-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_alter_pokemon_img_feeding"),
    ]

    operations = [
        migrations.AlterModelOptions(name="feeding", options={"ordering": ["-date"]},),
        migrations.AlterField(
            model_name="feeding",
            name="meal",
            field=models.CharField(
                choices=[
                    ("B", "Breakfast"),
                    ("L", "Lunch"),
                    ("S", "Snack"),
                    ("D", "Dinner"),
                    ("T", "Treat"),
                ],
                default="T",
                max_length=1,
                verbose_name="Meal Type",
            ),
        ),
    ]
