# Generated by Django 4.1.7 on 2023-04-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_alter_feeding_options_alter_feeding_meal"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="ready_to_levelup",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pokemon", name="level", field=models.IntegerField(default=5),
        ),
    ]
