# Generated by Django 4.1.7 on 2023-04-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_pokemon_ready_to_levelup_alter_pokemon_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon",
            old_name="ready_to_levelup",
            new_name="ready_to_level_up",
        ),
    ]
