# Generated by Django 4.1.7 on 2023-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_rename_ready_to_levelup_pokemon_ready_to_level_up"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="ready_to_level_up",
            field=models.BooleanField(default=True),
        ),
    ]
