# Generated by Django 4.1.7 on 2023-04-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_alter_pokemon_ready_to_level_up"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player", old_name="createdBy", new_name="ownedby",
        ),
    ]
