# Generated by Django 4.1.7 on 2023-04-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_remove_pokemon_in_pocket_pokemon_ownedat"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="in_pocket",
            field=models.BooleanField(default=True),
        ),
    ]
