# Generated by Django 4.1.7 on 2023-04-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0013_pokemon_in_pocket"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="is_leveled",
            field=models.BooleanField(default=False),
        ),
    ]
