# Generated by Django 4.1.7 on 2023-04-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0014_pokemon_is_leveled"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="pokemon_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="ready_to_level_up",
            field=models.BooleanField(default=False),
        ),
    ]
