# Generated by Django 4.1.7 on 2023-04-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0017_rename_evole_chains_pokemon_evolve_chains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon", name="evolve_chains", field=models.JSONField(),
        ),
    ]
