# Generated by Django 4.1.7 on 2023-04-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_alter_pokemon_evolve_chains"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="items",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player", name="money", field=models.IntegerField(default=5000),
        ),
    ]
