# Generated by Django 4.1.7 on 2023-04-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0019_player_items_player_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="ready_tp_evolve",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="player",
            name="items",
            field=models.JSONField(default={"thunder-stone": 1}),
        ),
    ]
