# Generated by Django 4.1.7 on 2023-04-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0020_pokemon_ready_tp_evolve_alter_player_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon",
            old_name="ready_tp_evolve",
            new_name="ready_to_evolve",
        ),
    ]
