# Generated by Django 4.1.7 on 2023-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0021_rename_ready_tp_evolve_pokemon_ready_to_evolve"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="img",
            field=models.CharField(
                default="https://www.kocpc.com.tw/wp-content/uploads/2016/09/1473059862-1058abae0dc372f4432cbea7fa123512.jpg",
                max_length=250,
            ),
        ),
    ]
