# Generated by Django 4.1.7 on 2023-04-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0022_player_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player", name="money", field=models.IntegerField(default=25000),
        ),
    ]
